
#Installing and calling tidyr package
install.packages('tidyr')
library(tidyr)
# Get the data
library(ona)
s_data <- onaDownload('Marketing_Survey_Form_1_1','onasupport','jmunene','jmg@Ona')

#Convert the data into a DF
s_data_df <- as.data.frame(s_data)
#Split all multiple choice questions into seperate columns
library(tidyr)

#Active Users
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ1, into = c("AQ1a", "AQ1b","AQ1c","AQ1d"), sep = " ,")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ2, into = c("AQ2a", "AQ2b","AQ2c","AQ2d","AQ2e","AQ2f"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ3, into = c("AQ3a", "AQ3b","AQ3c","AQ3d","AQ3e","AQ3f","AQ3g"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ5, into = c("AQ5a", "AQ5b","AQ5c","AQ5d","AQ5e","AQ5f","AQ5g","AQ5h","AQ5i","AQ5j","AQ5k","AQ5l"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ7, into = c("AQ7a", "AQ7b","AQ7c","AQ7d","AQ7e","AQ7f","AQ7g"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ9, into = c("AQ9a", "AQ9b","AQ9c","AQ9d","AQ9e","AQ9f","AQ9g"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Active_Users.ActiveQ11, into = c("AQ11a", "AQ11b","AQ11c","AQ11d","AQ11e"), sep = " ")
#Inactive Users
s_data_df <- separate(data = s_data_df, col = Inactive_Users.InactiveQ1, into = c("InQ1a", "InQ1b","InQ1c","InQ1d"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Inactive_Users.InactiveQ2, into = c("InQ2a", "InQ2b","InQ2c","InQ2d","InQ2e","InQ2f"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Inactive_Users.InactiveQ3, into = c("InQ3a", "InQ3b","InQ3c","InQ3d"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Inactive_Users.InactiveQ4, into = c("InQ4a", "InQ4b","InQ4c","InQ4d","InQ4e","InQ4f","InQ4g","InQ4h","InQ4i", "InQ4j","InQ4k","InQ4l"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Inactive_Users.InactiveQ5, into = c("InQ5a", "InQ5b","InQ5c","InQ5d","InQ5e"), sep = " ")
#Recently upgraded
s_data_df <- separate(data = s_data_df, col = Recently_Upgraded.UpgradedQ1, into = c("UpQ1a", "UpQ1b","UpQ1c","UpQ1d"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Recently_Upgraded.UpgradedQ3, into = c("UpQ3a", "UpQ3b","UpQ3c","UpQ3d","UpQ3e", "UpQ3f","UpQ3g","UpQ3h","UpQ3i", "UpQ3j","UpQ3k","UpQ3l"), sep = " ")
s_data_df <- separate(data = s_data_df, col = Recently_Upgraded.UpgradedQ4, into = c("UpQ4a", "UpQ4b","UpQ4c","UpQ4d"), sep = " ")


# Replace labels with names

#Q1
levels(s_data_df$Screener_Questions.ScreenerQ1)[levels(s_data_df$Screener_Questions.ScreenerQ1)==1] <- 'Active user'
levels(s_data_df$Screener_Questions.ScreenerQ1)[levels(s_data_df$Screener_Questions.ScreenerQ1)==2] <- 'Once in a while'
levels(s_data_df$Screener_Questions.ScreenerQ1)[levels(s_data_df$Screener_Questions.ScreenerQ1)==3] <- 'Rarely'
levels(s_data_df$Screener_Questions.ScreenerQ1)[levels(s_data_df$Screener_Questions.ScreenerQ1)==4] <- 'Other'
#Q2
levels(s_data_df$Screener_Questions.ScreenerQ2)[levels(s_data_df$Screener_Questions.ScreenerQ2)==1] <- 'Yes'
levels(s_data_df$Screener_Questions.ScreenerQ2)[levels(s_data_df$Screener_Questions.ScreenerQ2)==2] <- 'No'
#Q3
levels(s_data_df$Screener_Questions.ScreenerQ3)[levels(s_data_df$Screener_Questions.ScreenerQ3)==1] <- 'Yes'
levels(s_data_df$Screener_Questions.ScreenerQ3)[levels(s_data_df$Screener_Questions.ScreenerQ3)==2] <- 'No'

#ActiveUsersQ4
levels(s_data_df$Active_Users.ActiveQ4)[levels(s_data_df$Active_Users.ActiveQ4)==1] <- 'Yes'
levels(s_data_df$Active_Users.ActiveQ4)[levels(s_data_df$Active_Users.ActiveQ4)==2] <- 'No'

#ActiveUsersQ6
levels(s_data_df$Active_Users.ActiveQ6)[levels(s_data_df$Active_Users.ActiveQ6)==1] <- 'Yes'
levels(s_data_df$Active_Users.ActiveQ6)[levels(s_data_df$Active_Users.ActiveQ6)==2] <- 'No'

#Active usersQ8
levels(s_data_df$Active_Users.ActiveQ8)[levels(s_data_df$Active_Users.ActiveQ8)==1] <- 'Yes'
levels(s_data_df$Active_Users.ActiveQ8)[levels(s_data_df$Active_Users.ActiveQ8)==2] <- 'No'

#ActiveUsersQ10
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==1] <- 'Comfortable with free account'
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==2] <- 'Only use Ona for Data collection'
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==3] <- 'Its too expensive'
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==4] <- 'Was just testing Ona'
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==5] <- 'want to continue testing Ona'
levels(s_data_df$Active_Users.ActiveQ10)[levels(s_data_df$Active_Users.ActiveQ10)==6] <- 'Other'

#UpgradedQ2
levels(s_data_df$Recently_Upgraded.UpgradedQ2)[levels(s_data_df$Recently_Upgraded.UpgradedQ2)==1] <- 'Yes'
levels(s_data_df$Recently_Upgraded.UpgradedQ2)[levels(s_data_df$Recently_Upgraded.UpgradedQ2)==2] <- 'No'

#GeneralQ2
levels(s_data_df$GeneralQ2)[levels(s_data_df$GeneralQ2)==1] <- 'Yes'
levels(s_data_df$GeneralQ2)[levels(s_data_df$GeneralQ2)==2] <- 'No'

#GeneralQ3
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==1] <- 'Very unlikely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==2] <- 'Very unlikely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==3] <- 'Unlikely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==4] <- 'Unlikely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==5] <- 'Somewhat likely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==6] <- 'Somewhat likely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==7] <- 'Likely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==8] <- 'Likely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==9] <- 'Very likely'
levels(s_data_df$GeneralQ3)[levels(s_data_df$GeneralQ3)==10] <- 'Very likely'

levels(s_data_df$GeneralQ1)[levels(s_data_df$GeneralQ1)==2] <- 'very likely'
#replacing labes with names 
#Active free users
#How did you know hear about Ona?
s_data_df$AQ1a <- replace(s_data_df$AQ1a, s_data_df$AQ1a=="1", "Suggested by a friend")
s_data_df$AQ1a <- replace(s_data_df$AQ1a, s_data_df$AQ1a=="2", "Online ads")
s_data_df$AQ1a <- replace(s_data_df$AQ1a, s_data_df$AQ1a=="3", "A conference")
s_data_df$AQ1a <- replace(s_data_df$AQ1a, s_data_df$AQ1a=="4", "Other")

s_data_df$AQ1b <- replace(s_data_df$AQ1b, s_data_df$AQ1b=="1", "Suggested by a friend")
s_data_df$AQ1b <- replace(s_data_df$AQ1b, s_data_df$AQ1b=="2", "Online ads")
s_data_df$AQ1b <- replace(s_data_df$AQ1b, s_data_df$AQ1b=="3", "A conference")
s_data_df$AQ1b <- replace(s_data_df$AQ1b, s_data_df$AQ1b=="4", "Other")

s_data_df$AQ1c <- replace(s_data_df$AQ1c, s_data_df$AQ1c=="1", "Suggested by a friend")
s_data_df$AQ1c <- replace(s_data_df$AQ1c, s_data_df$AQ1c=="2", "Online ads")
s_data_df$AQ1c <- replace(s_data_df$AQ1c, s_data_df$AQ1c=="3", "A conferene")
s_data_df$AQ1c <- replace(s_data_df$AQ1c, s_data_df$AQ1c=="4", "Other")

s_data_df$AQ1d <- replace(s_data_df$AQ1d, s_data_df$AQ1d=="1", "Suggested by a friend")
s_data_df$AQ1d <- replace(s_data_df$AQ1d, s_data_df$AQ1d=="2", "Online ads")
s_data_df$AQ1d <- replace(s_data_df$AQ1d, s_data_df$AQ1d=="3", "A conference")
s_data_df$AQ1d <- replace(s_data_df$AQ1d, s_data_df$AQ1d=="4", "Other")

#Why did you sign up to use Ona?
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="1", "Collect data only")
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="2", "Collect data and create charts")
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="3", "Test XLSForms")
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="4", "View collected data") 
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="5", "View charts")
s_data_df$AQ2a <- replace(s_data_df$AQ2a, s_data_df$AQ2a=="6", "Other") 

s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="1", "Collect data only")
s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="2", "Collect data and create charts")
s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="3", "Test XLSForms")
s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="4", "View collected data") 
s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="5", "View charts")
s_data_df$AQ2b <- replace(s_data_df$AQ2b, s_data_df$AQ2b=="6", "Other") 

s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="1", "Collect data only")
s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="2", "Collect data and create charts")
s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="3", "Test XLSForms")
s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="4", "View collected data") 
s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="5", "View charts")
s_data_df$AQ2c <- replace(s_data_df$AQ2c, s_data_df$AQ2c=="6", "Other") 

s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="1", "Collect data only")
s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="2", "Collect data and create charts")
s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="3", "Test XLSForms")
s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="4", "View collected data") 
s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="5", "View charts")
s_data_df$AQ2d <- replace(s_data_df$AQ2d, s_data_df$AQ2d=="6", "Other") 

s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="1", "Collect data only")
s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="2", "Collect data and create charts")
s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="3", "Test XLSForms")
s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="4", "View collected data") 
s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="5", "View charts")
s_data_df$AQ2e <- replace(s_data_df$AQ2e, s_data_df$AQ2e=="6", "Other") 

s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="1", "Collect data only")
s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="2", "Collect data and create charts")
s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="3", "Test XLSForms")
s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="4", "View collected data") 
s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="5", "View charts")
s_data_df$AQ2f <- replace(s_data_df$AQ2f, s_data_df$AQ2f=="6", "Other") 

#What's your role in the data collection process?
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="1", "Enumerator/Interviewer")
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="2", "Project Manager")
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="3", "M&E Expert")
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="4", "Data Analyst") 
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="5", "XLSForm Expert")
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3a <- replace(s_data_df$AQ3a, s_data_df$AQ3a=="7", "Other")

s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="1", "Enumerator/Interviewer")
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="2", "Project Manager")
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="3", "M&E Expert")
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="4", "Data Analyst") 
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="5", "XLSForm Expert")
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3b <- replace(s_data_df$AQ3b, s_data_df$AQ3b=="7", "Other")

s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="1", "Enumerator/Interviewer")
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="2", "Project Manager")
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="3", "M&E Expert")
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="4", "Data Analyst") 
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="5", "XLSForm Expert")
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3c <- replace(s_data_df$AQ3c, s_data_df$AQ3c=="7", "Other")

s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="1", "Enumerator/Interviewer")
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="2", "Project Manager")
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="3", "M&E Expert")
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="4", "Data Analyst") 
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="5", "XLSForm Expert")
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3d <- replace(s_data_df$AQ3d, s_data_df$AQ3d=="7", "Other")

s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="1", "Enumerator/Interviewer")
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="2", "Project Manager")
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="3", "M&E Expert")
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="4", "Data Analyst") 
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="5", "XLSForm Expert")
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3e <- replace(s_data_df$AQ3e, s_data_df$AQ3e=="7", "Other")

s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="1", "Enumerator/Interviewer")
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="2", "Project Manager")
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="3", "M&E Expert")
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="4", "Data Analyst") 
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="5", "XLSForm Expert")
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3f <- replace(s_data_df$AQ3f, s_data_df$AQ3f=="7", "Other")

s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="1", "Enumerator/Interviewer")
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="2", "Project Manager")
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="3", "M&E Expert")
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="4", "Data Analyst") 
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="5", "XLSForm Expert")
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="6", "Data Analyst/XLSForm Expert")
s_data_df$AQ3g <- replace(s_data_df$AQ3g, s_data_df$AQ3g=="7", "Other")

#What are the challenges you've faced when using Ona?
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="1", "Creating XLSForms")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="2", "Signing up/ Creating accounts")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="3", "Sharing projects")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="4", "Uploading data") 
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="5", "Viewing collected data")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="6", "Editing collected data")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="7", "Deleting collected data")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="8", "Using the webform")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="9", "Downloading data")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="10", "Downloading multimedia")
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="11", "Downloading charts") 
s_data_df$AQ5a <- replace(s_data_df$AQ5a, s_data_df$AQ5a=="12", "Other")

s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="1", "Creating XLSForms")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="2", "Signing up/ Creating accounts")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="3", "Sharing projects")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="4", "Uploading data") 
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="5", "Viewing collected data")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="6", "Editing collected data")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="7", "Deleting collected data")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="8", "Using the webform")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="9", "Downloading data")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="10", "Downloading multimedia")
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="11", "Downloading charts") 
s_data_df$AQ5b <- replace(s_data_df$AQ5b, s_data_df$AQ5b=="12", "Other")

s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="1", "Creating XLSForms")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="2", "Signing up/ Creating accounts")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="3", "Sharing projects")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="4", "Uploading data") 
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="5", "Viewing collected data")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="6", "Editing collected data")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="7", "Deleting collected data")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="8", "Using the webform")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="9", "Downloading data")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="10", "Downloading multimedia")
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="11", "Downloading charts") 
s_data_df$AQ5c <- replace(s_data_df$AQ5c, s_data_df$AQ5c=="12", "Other")

s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="1", "Creating XLSForms")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="2", "Signing up/ Creating accounts")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="3", "Sharing projects")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="4", "Uploading data") 
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="5", "Viewing collected data")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="6", "Editing collected data")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="7", "Deleting collected data")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="8", "Using the webform")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="9", "Downloading data")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="10", "Downloading multimedia")
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="11", "Downloading charts") 
s_data_df$AQ5d <- replace(s_data_df$AQ5d, s_data_df$AQ5d=="12", "Other")

s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="1", "Creating XLSForms")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="2", "Signing up/ Creating accounts")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="3", "Sharing projects")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="4", "Uploading data") 
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="5", "Viewing collected data")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="6", "Editing collected data")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="7", "Deleting collected data")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="8", "Using the webform")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="9", "Downloading data")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="10", "Downloading multimedia")
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="11", "Downloading charts") 
s_data_df$AQ5e <- replace(s_data_df$AQ5e, s_data_df$AQ5e=="12", "Other")

s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="1", "Creating XLSForms")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="2", "Signing up/ Creating accounts")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="3", "Sharing projects")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="4", "Uploading data") 
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="5", "Viewing collected data")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="6", "Editing collected data")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="7", "Deleting collected data")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="8", "Using the webform")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="9", "Downloading data")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="10", "Downloading multimedia")
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="11", "Downloading charts") 
s_data_df$AQ5f <- replace(s_data_df$AQ5f, s_data_df$AQ5f=="12", "Other")

s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="1", "Creating XLSForms")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="2", "Signing up/ Creating accounts")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="3", "Sharing projects")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="4", "Uploading data") 
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="5", "Viewing collected data")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="6", "Editing collected data")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="7", "Deleting collected data")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="8", "Using the webform")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="9", "Downloading data")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="10", "Downloading multimedia")
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="11", "Downloading charts") 
s_data_df$AQ5g <- replace(s_data_df$AQ5g, s_data_df$AQ5g=="12", "Other")

s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="1", "Creating XLSForms")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="2", "Signing up/ Creating accounts")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="3", "Sharing projects")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="4", "Uploading data") 
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="5", "Viewing collected data")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="6", "Editing collected data")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="7", "Deleting collected data")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="8", "Using the webform")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="9", "Downloading data")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="10", "Downloading multimedia")
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="11", "Downloading charts") 
s_data_df$AQ5h <- replace(s_data_df$AQ5h, s_data_df$AQ5h=="12", "Other")

s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="1", "Creating XLSForms")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="2", "Signing up/ Creating accounts")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="3", "Sharing projects")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="4", "Uploading data") 
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="5", "Viewing collected data")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="6", "Editing collected data")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="7", "Deleting collected data")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="8", "Using the webform")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="9", "Downloading data")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="10", "Downloading multimedia")
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="11", "Downloading charts") 
s_data_df$AQ5i <- replace(s_data_df$AQ5i, s_data_df$AQ5i=="12", "Other")

s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="1", "Creating XLSForms")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j="2", "Signing up/ Creating accounts")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="3", "Sharing projects")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="4", "Uploading data") 
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="5", "Viewing collected data")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="6", "Editing collected data")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="7", "Deleting collected data")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="8", "Using the webform")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="9", "Downloading data")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="10", "Downloading multimedia")
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="11", "Downloading charts") 
s_data_df$AQ5j <- replace(s_data_df$AQ5j, s_data_df$AQ5j=="12", "Other")

s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="1", "Creating XLSForms")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="2", "Signing up/ Creating accounts")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="3", "Sharing projects")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="4", "Uploading data") 
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="5", "Viewing collected data")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="6", "Editing collected data")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="7", "Deleting collected data")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="8", "Using the webform")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="9", "Downloading data")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="10", "Downloading multimedia")
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="11", "Downloading charts") 
s_data_df$AQ5k <- replace(s_data_df$AQ5k, s_data_df$AQ5k=="12", "Other")

s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="1", "Creating XLSForms")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="2", "Signing up/ Creating accounts")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="3", "Sharing projects")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="4", "Uploading data") 
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="5", "Viewing collected data")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="6", "Editing collected data")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="7", "Deleting collected data")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="8", "Using the webform")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="9", "Downloading data")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="10", "Downloading multimedia")
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="11", "Downloading charts") 
s_data_df$AQ5l <- replace(s_data_df$AQ5l, s_data_df$AQ5l=="12", "Other")

#Which features are you aware of?
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="1", "Unlimited form submissions")
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="2", "Priority support")
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="3", "Ona Apps")
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="4", "Filtered datasets") 
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="5", "XLS Reports")
s_data_df$AQ7a <- replace(s_data_df$AQ7a, s_data_df$AQ7a=="6", "Other")

s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="1", "Unlimited form submissions")
s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="2", "Priority support")
s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="3", "Ona Apps")
s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="4", "Filtered datasets") 
s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="5", "XLS Reports")
s_data_df$AQ7b <- replace(s_data_df$AQ7b, s_data_df$AQ7b=="6", "Other")

s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="1", "Unlimited form submissions")
s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="2", "Priority support")
s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="3", "Ona Apps")
s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="4", "Filtered datasets") 
s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="5", "XLS Reports")
s_data_df$AQ7c <- replace(s_data_df$AQ7c, s_data_df$AQ7c=="6", "Other")

s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="1", "Unlimited form submissions")
s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="2", "Priority support")
s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="3", "Ona Apps")
s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="4", "Filtered datasets") 
s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="5", "XLS Reports")
s_data_df$AQ7d <- replace(s_data_df$AQ7d, s_data_df$AQ7d=="6", "Other")

s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="1", "Unlimited form submissions")
s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="2", "Priority support")
s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="3", "Ona Apps")
s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="4", "Filtered datasets") 
s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="5", "XLS Reports")
s_data_df$AQ7e <- replace(s_data_df$AQ7e, s_data_df$AQ7e=="6", "Other")

s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="1", "Unlimited form submissions")
s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="2", "Priority support")
s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="3", "Ona Apps")
s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="4", "Filtered datasets") 
s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="5", "XLS Reports")
s_data_df$AQ7f <- replace(s_data_df$AQ7f, s_data_df$AQ7f=="6", "Other")

#Which of these features are you interested in using?
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="1", "Unlimited form submissions")
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="2", "Priority support")
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="3", "Ona Apps")
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="4", "Filtered datasets") 
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="5", "XLS Reports")
s_data_df$AQ9a <- replace(s_data_df$AQ9a, s_data_df$AQ9a=="6", "Other")

s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="1", "Unlimited form submissions")
s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="2", "Priority support")
s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="3", "Ona Apps")
s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="4", "Filtered datasets") 
s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="5", "XLS Reports")
s_data_df$AQ9b <- replace(s_data_df$AQ9b, s_data_df$AQ9b=="6", "Other")

s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="1", "Unlimited form submissions")
s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="2", "Priority support")
s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="3", "Ona Apps")
s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="4", "Filtered datasets") 
s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="5", "XLS Reports")
s_data_df$AQ9c <- replace(s_data_df$AQ9c, s_data_df$AQ9c=="6", "Other")

s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="1", "Unlimited form submissions")
s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="2", "Priority support")
s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="3", "Ona Apps")
s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="4", "Filtered datasets") 
s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="5", "XLS Reports")
s_data_df$AQ9d <- replace(s_data_df$AQ9d, s_data_df$AQ9d=="6", "Other")

s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="1", "Unlimited form submissions")
s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="2", "Priority support")
s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="3", "Ona Apps")
s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="4", "Filtered datasets") 
s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="5", "XLS Reports")
s_data_df$AQ9e <- replace(s_data_df$AQ9e, s_data_df$AQ9e=="6", "Other")

s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="1", "Unlimited form submissions")
s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="2", "Priority support")
s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="3", "Ona Apps")
s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="4", "Filtered datasets") 
s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="5", "XLS Reports")
s_data_df$AQ9f <- replace(s_data_df$AQ9f, s_data_df$AQ9f=="6", "Other")

#As a free user, what would you want to see improved?
s_data_df$AQ11a<- replace(s_data_df$AQ11a, s_data_df$AQ11a=="1", "User Interface (UI)")
s_data_df$AQ11a<- replace(s_data_df$AQ11a, s_data_df$AQ11a=="2", "Form creation (Builder)")
s_data_df$AQ11a<- replace(s_data_df$AQ11a, s_data_df$AQ11a=="3", "More chart types")
s_data_df$AQ11a<- replace(s_data_df$AQ11a, s_data_df$AQ11a=="4", "Other")
s_data_df$AQ11a<- replace(s_data_df$AQ11a, s_data_df$AQ11a=="5", "Ona Collect")

s_data_df$AQ11b<- replace(s_data_df$AQ11b, s_data_df$AQ11b=="1", "User Interface (UI)")
s_data_df$AQ11b<- replace(s_data_df$AQ11b, s_data_df$AQ11b=="2", "Form creation (Builder)")
s_data_df$AQ11b<- replace(s_data_df$AQ11b, s_data_df$AQ11b=="3", "More chart types")
s_data_df$AQ11b<- replace(s_data_df$AQ11b, s_data_df$AQ11b=="4", "Other")
s_data_df$AQ11b<- replace(s_data_df$AQ11b, s_data_df$AQ11b=="5", "Ona Collect")

s_data_df$AQ11c<- replace(s_data_df$AQ11c, s_data_df$AQ11c=="1", "User Interface (UI)")
s_data_df$AQ11c<- replace(s_data_df$AQ11c, s_data_df$AQ11c=="2", "Form creation (Builder)")
s_data_df$AQ11c<- replace(s_data_df$AQ11c, s_data_df$AQ11c=="3", "More chart types")
s_data_df$AQ11c<- replace(s_data_df$AQ11c, s_data_df$AQ11c=="4", "Other")
s_data_df$AQ11c<- replace(s_data_df$AQ11c, s_data_df$AQ11c=="5", "Ona Collect")

s_data_df$AQ11d<- replace(s_data_df$AQ11d, s_data_df$AQ11d=="1", "User Interface (UI)")
s_data_df$AQ11d<- replace(s_data_df$AQ11d, s_data_df$AQ11d=="2", "Form creation (Builder)")
s_data_df$AQ11d<- replace(s_data_df$AQ11d, s_data_df$AQ11d=="3", "More chart types")
s_data_df$AQ11d<- replace(s_data_df$AQ11d, s_data_df$AQ11d=="4", "Other")
s_data_df$AQ11d<- replace(s_data_df$AQ11d, s_data_df$AQ11d=="5", "Ona Collect")

s_data_df$AQ11e<- replace(s_data_df$AQ11e, s_data_df$AQ11e=="1", "User Interface (UI)")
s_data_df$AQ11e<- replace(s_data_df$AQ11e, s_data_df$AQ11e=="2", "Form creation (Builder)")
s_data_df$AQ11e<- replace(s_data_df$AQ11e, s_data_df$AQ11e=="3", "More chart types")
s_data_df$AQ11e<- replace(s_data_df$AQ11e, s_data_df$AQ11e=="4", "Other")
s_data_df$AQ11e<- replace(s_data_df$AQ11e, s_data_df$AQ11e=="5", "Ona Collect")

#Inactive Users
#How did you hear about Ona?

s_data_df$InQ1a <- replace(s_data_df$InQ1a, s_data_df$InQ1a=="1", "Suggested by a friend")
s_data_df$InQ1a <- replace(s_data_df$InQ1a, s_data_df$InQ1a=="2", "Online ads")
s_data_df$InQ1a <- replace(s_data_df$InQ1a, s_data_df$InQ1a=="3", "A conference  where Ona was present")
s_data_df$InQ1a <- replace(s_data_df$InQ1a, s_data_df$InQ1a=="4", "Other")

s_data_df$InQ1b <- replace(s_data_df$InQ1b, s_data_df$InQ1b=="1", "Suggested by a friend")
s_data_df$InQ1b <- replace(s_data_df$InQ1b, s_data_df$InQ1b=="2", "Online ads")
s_data_df$InQ1b <- replace(s_data_df$InQ1b, s_data_df$InQ1b=="3", "A conference  where Ona was present")
s_data_df$InQ1b <- replace(s_data_df$InQ1b, s_data_df$InQ1b=="4", "Other")

s_data_df$InQ1c <- replace(s_data_df$InQ1c, s_data_df$InQ1c=="1", "Suggested by a friend")
s_data_df$InQ1c <- replace(s_data_df$InQ1c, s_data_df$InQ1c=="2", "Online ads")
s_data_df$InQ1c <- replace(s_data_df$InQ1c, s_data_df$InQ1c=="3", "A conference  where Ona was present")
s_data_df$InQ1c <- replace(s_data_df$InQ1c, s_data_df$InQ1c=="4", "Other")

s_data_df$InQ1d <- replace(s_data_df$InQ1d, s_data_df$InQ1d=="1", "Suggested by a friend")
s_data_df$InQ1d <- replace(s_data_df$InQ1d, s_data_df$InQ1d=="2", "Online ads")
s_data_df$InQ1d <- replace(s_data_df$InQ1d, s_data_df$InQ1d=="3", "A conference  where Ona was present")
s_data_df$InQ1d <- replace(s_data_df$InQ1d, s_data_df$InQ1d=="4", "Other")

#What would you like to see improved in Ona?
s_data_df$InQ5a<- replace(s_data_df$InQ5a, s_data_df$InQ5a=="1", "User Interface (UI)")
s_data_df$InQ5a<- replace(s_data_df$InQ5a, s_data_df$InQ5a=="2", "Form creation (Builder)")
s_data_df$InQ5a<- replace(s_data_df$InQ5a, s_data_df$InQ5a=="3", "More chart types")
s_data_df$InQ5a<- replace(s_data_df$InQ5a, s_data_df$InQ5a=="4", "Other")
s_data_df$InQ5a<- replace(s_data_df$InQ5a, s_data_df$InQ5a=="5", "Ona Collect")

s_data_df$InQ5b<- replace(s_data_df$InQ5b, s_data_df$InQ5b=="1", "User Interface (UI)")
s_data_df$InQ5b<- replace(s_data_df$InQ5b, s_data_df$InQ5b=="2", "Form creation (Builder)")
s_data_df$InQ5b<- replace(s_data_df$InQ5b, s_data_df$InQ5b=="3", "More chart types")
s_data_df$InQ5b<- replace(s_data_df$InQ5b, s_data_df$InQ5b=="4", "Other")
s_data_df$InQ5b<- replace(s_data_df$InQ5b, s_data_df$InQ5b=="5", "Ona Collect")

s_data_df$InQ5c<- replace(s_data_df$InQ5c, s_data_df$InQ5c=="1", "User Interface (UI)")
s_data_df$InQ5c<- replace(s_data_df$InQ5c, s_data_df$InQ5c=="2", "Form creation (Builder)")
s_data_df$InQ5c<- replace(s_data_df$InQ5c, s_data_df$InQ5c=="3", "More chart types")
s_data_df$InQ5c<- replace(s_data_df$InQ5c, s_data_df$InQ5c=="4", "Other")
s_data_df$InQ5c<- replace(s_data_df$InQ5c, s_data_df$InQ5c=="5", "Ona Collect")

s_data_df$InQ5d<- replace(s_data_df$InQ5d, s_data_df$InQ5d=="1", "User Interface (UI)")
s_data_df$InQ5d<- replace(s_data_df$InQ5d, s_data_df$InQ5d=="2", "Form creation (Builder)")
s_data_df$InQ5d<- replace(s_data_df$InQ5d, s_data_df$InQ5d=="3", "More chart types")
s_data_df$InQ5d<- replace(s_data_df$InQ5d, s_data_df$InQ5d=="4", "Other")
s_data_df$InQ5d<- replace(s_data_df$InQ5d, s_data_df$InQ5d=="5", "Ona Collect")

s_data_df$InQ5e<- replace(s_data_df$InQ5e, s_data_df$InQ5e=="1", "User Interface (UI)")
s_data_df$InQ5e<- replace(s_data_df$InQ5e, s_data_df$InQ5e=="2", "Form creation (Builder)")
s_data_df$InQ5e<- replace(s_data_df$InQ5e, s_data_df$InQ5e=="3", "More chart types")
s_data_df$InQ5e<- replace(s_data_df$InQ5e, s_data_df$InQ5e=="4", "Other")
s_data_df$InQ5e<- replace(s_data_df$InQ5e, s_data_df$InQ5e=="5", "Ona Collect")

#What challenges did you face with Ona?
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="1", "Creating XLSForms")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="2", "Signing up/ Creating accounts")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="3", "Sharing projects")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="4", "Uploading data") 
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="5", "Viewing collected data")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="6", "Editing collected data")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="7", "Deleting collected data")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="8", "Using the webform")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="9", "Downloading data")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="10", "Downloading multimedia")
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="11", "Downloading charts") 
s_data_df$InQ4a <- replace(s_data_df$InQ4a, s_data_df$InQ4a=="12", "Other")

s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="1", "Creating XLSForms")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="2", "Signing up/ Creating accounts")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="3", "Sharing projects")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="4", "Uploading data") 
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="5", "Viewing collected data")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="6", "Editing collected data")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="7", "Deleting collected data")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="8", "Using the webform")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="9", "Downloading data")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="10", "Downloading multimedia")
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="11", "Downloading charts") 
s_data_df$InQ4b <- replace(s_data_df$InQ4b, s_data_df$InQ4b=="12", "Other")

s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="1", "Creating XLSForms")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="2", "Signing up/ Creating accounts")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="3", "Sharing projects")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="4", "Uploading data") 
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="5", "Viewing collected data")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="6", "Editing collected data")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="7", "Deleting collected data")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="8", "Using the webform")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="9", "Downloading data")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="10", "Downloading multimedia")
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="11", "Downloading charts") 
s_data_df$InQ4c <- replace(s_data_df$InQ4c, s_data_df$InQ4c=="12", "Other")

s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="1", "Creating XLSForms")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="2", "Signing up/ Creating accounts")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="3", "Sharing projects")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="4", "Uploading data") 
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="5", "Viewing collected data")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="6", "Editing collected data")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="7", "Deleting collected data")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="8", "Using the webform")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="9", "Downloading data")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="10", "Downloading multimedia")
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="11", "Downloading charts") 
s_data_df$InQ4d <- replace(s_data_df$InQ4d, s_data_df$InQ4d=="12", "Other")

s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="1", "Creating XLSForms")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="2", "Signing up/ Creating accounts")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="3", "Sharing projects")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="4", "Uploading data") 
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="5", "Viewing collected data")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="6", "Editing collected data")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="7", "Deleting collected data")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="8", "Using the webform")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="9", "Downloading data")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="10", "Downloading multimedia")
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="11", "Downloading charts") 
s_data_df$InQ4e <- replace(s_data_df$InQ4e, s_data_df$InQ4e=="12", "Other")

s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="1", "Creating XLSForms")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="2", "Signing up/ Creating accounts")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="3", "Sharing projects")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="4", "Uploading data") 
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="5", "Viewing collected data")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="6", "Editing collected data")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="7", "Deleting collected data")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="8", "Using the webform")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="9", "Downloading data")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="10", "Downloading multimedia")
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="11", "Downloading charts") 
s_data_df$InQ4f <- replace(s_data_df$InQ4f, s_data_df$InQ4f=="12", "Other")

s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="1", "Creating XLSForms")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="2", "Signing up/ Creating accounts")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="3", "Sharing projects")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="4", "Uploading data") 
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="5", "Viewing collected data")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="6", "Editing collected data")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="7", "Deleting collected data")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="8", "Using the webform")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="9", "Downloading data")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="10", "Downloading multimedia")
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="11", "Downloading charts") 
s_data_df$InQ4g <- replace(s_data_df$InQ4g, s_data_df$InQ4g=="12", "Other")

s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="1", "Creating XLSForms")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="2", "Signing up/ Creating accounts")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="3", "Sharing projects")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="4", "Uploading data") 
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="5", "Viewing collected data")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="6", "Editing collected data")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="7", "Deleting collected data")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="8", "Using the webform")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="9", "Downloading data")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="10", "Downloading multimedia")
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="11", "Downloading charts") 
s_data_df$InQ4h <- replace(s_data_df$InQ4h, s_data_df$InQ4h=="12", "Other")

s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="1", "Creating XLSForms")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="2", "Signing up/ Creating accounts")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="3", "Sharing projects")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="4", "Uploading data") 
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="5", "Viewing collected data")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="6", "Editing collected data")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="7", "Deleting collected data")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="8", "Using the webform")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="9", "Downloading data")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="10", "Downloading multimedia")
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="11", "Downloading charts") 
s_data_df$InQ4i <- replace(s_data_df$InQ4i, s_data_df$InQ4i=="12", "Other")

s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="1", "Creating XLSForms")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="2", "Signing up/ Creating accounts")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="3", "Sharing projects")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="4", "Uploading data") 
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="5", "Viewing collected data")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="6", "Editing collected data")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="7", "Deleting collected data")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="8", "Using the webform")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="9", "Downloading data")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="10", "Downloading multimedia")
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="11", "Downloading charts") 
s_data_df$InQ4j <- replace(s_data_df$InQ4j, s_data_df$InQ4j=="12", "Other")

s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="1", "Creating XLSForms")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="2", "Signing up/ Creating accounts")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="3", "Sharing projects")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="4", "Uploading data") 
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="5", "Viewing collected data")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="6", "Editing collected data")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="7", "Deleting collected data")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="8", "Using the webform")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="9", "Downloading data")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="10", "Downloading multimedia")
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="11", "Downloading charts") 
s_data_df$InQ4k <- replace(s_data_df$InQ4k, s_data_df$InQ4k=="12", "Other")

s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="1", "Creating XLSForms")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="2", "Signing up/ Creating accounts")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="3", "Sharing projects")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="4", "Uploading data") 
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="5", "Viewing collected data")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="6", "Editing collected data")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="7", "Deleting collected data")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="8", "Using the webform")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="9", "Downloading data")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="10", "Downloading multimedia")
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="11", "Downloading charts") 
s_data_df$InQ4l <- replace(s_data_df$InQ4l, s_data_df$InQ4l=="12", "Other")

#Upgraded users
#what are the challenges you faced using Ona?
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="1", "Creating XLSForms")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="3", "Sharing projects")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="4", "Uploading data")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="5", "Viewing collected data")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="6", "Editing collected data")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="7", "Deleting collected data")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="8", "Using the webform")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="9", "Downloading data")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="10", "Downloading multimedia")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="11", "Downloading charts")
s_data_df$UpQ3a <- replace(s_data_df$UpQ3a, s_data_df$UpQ3a=="12", "Other")

s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="1", "Creating XLSForms")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="3", "Sharing projects")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="4", "Uploading data")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="5", "Viewing collected data")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="6", "Editing collected data")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="7", "Deleting collected data")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="8", "Using the webform")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="9", "Downloading data")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="10", "Downloading multimedia")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="11", "Downloading charts")
s_data_df$UpQ3b <- replace(s_data_df$UpQ3b, s_data_df$UpQ3b=="12", "Other")

s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="1", "Creating XLSForms")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="3", "Sharing projects")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="4", "Uploading data")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="5", "Viewing collected data")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="6", "Editing collected data")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="7", "Deleting collected data")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="8", "Using the webform")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="9", "Downloading data")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="10", "Downloading multimedia")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="11", "Downloading charts")
s_data_df$UpQ3c <- replace(s_data_df$UpQ3c, s_data_df$UpQ3c=="12", "Other")

s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="1", "Creating XLSForms")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="3", "Sharing projects")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="4", "Uploading data")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="5", "Viewing collected data")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="6", "Editing collected data")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="7", "Deleting collected data")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="8", "Using the webform")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="9", "Downloading data")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="10", "Downloading multimedia")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="11", "Downloading charts")
s_data_df$UpQ3d <- replace(s_data_df$UpQ3d, s_data_df$UpQ3d=="12", "Other")

s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="1", "Creating XLSForms")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="3", "Sharing projects")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="4", "Uploading data")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="5", "Viewing collected data")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="6", "Editing collected data")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="7", "Deleting collected data")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="8", "Using the webform")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="9", "Downloading data")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="10", "Downloading multimedia")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="11", "Downloading charts")
s_data_df$UpQ3e <- replace(s_data_df$UpQ3e, s_data_df$UpQ3e=="12", "Other")

s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="1", "Creating XLSForms")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="3", "Sharing projects")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="4", "Uploading data")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="5", "Viewing collected data")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="6", "Editing collected data")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="7", "Deleting collected data")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="8", "Using the webform")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="9", "Downloading data")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="10", "Downloading multimedia")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="11", "Downloading charts")
s_data_df$UpQ3f <- replace(s_data_df$UpQ3f, s_data_df$UpQ3f=="12", "Other")

s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="1", "Creating XLSForms")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="3", "Sharing projects")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="4", "Uploading data")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="5", "Viewing collected data")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="6", "Editing collected data")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="7", "Deleting collected data")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="8", "Using the webform")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="9", "Downloading data")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="10", "Downloading multimedia")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="11", "Downloading charts")
s_data_df$UpQ3g <- replace(s_data_df$UpQ3g, s_data_df$UpQ3g=="12", "Other")

s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="1", "Creating XLSForms")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="3", "Sharing projects")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="4", "Uploading data")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="5", "Viewing collected data")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="6", "Editing collected data")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="7", "Deleting collected data")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="8", "Using the webform")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="9", "Downloading data")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="10", "Downloading multimedia")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="11", "Downloading charts")
s_data_df$UpQ3h <- replace(s_data_df$UpQ3h, s_data_df$UpQ3h=="12", "Other")

s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="1", "Creating XLSForms")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="3", "Sharing projects")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="4", "Uploading data")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="5", "Viewing collected data")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="6", "Editing collected data")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="7", "Deleting collected data")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="8", "Using the webform")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="9", "Downloading data")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="10", "Downloading multimedia")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="11", "Downloading charts")
s_data_df$UpQ3i <- replace(s_data_df$UpQ3i, s_data_df$UpQ3i=="12", "Other")

s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="1", "Creating XLSForms")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="3", "Sharing projects")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="4", "Uploading data")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="5", "Viewing collected data")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="6", "Editing collected data")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="7", "Deleting collected data")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="8", "Using the webform")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="9", "Downloading data")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="10", "Downloading multimedia")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="11", "Downloading charts")
s_data_df$UpQ3j <- replace(s_data_df$UpQ3j, s_data_df$UpQ3j=="12", "Other")

s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="1", "Creating XLSForms")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="3", "Sharing projects")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="4", "Uploading data")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="5", "Viewing collected data")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="6", "Editing collected data")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="7", "Deleting collected data")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="8", "Using the webform")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="9", "Downloading data")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="10", "Downloading multimedia")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="11", "Downloading charts")
s_data_df$UpQ3k <- replace(s_data_df$UpQ3k, s_data_df$UpQ3k=="12", "Other")


s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="1", "Creating XLSForms")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="2", "Signing up/ Creating accounts")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="3", "Sharing projects")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="4", "Uploading data")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="5", "Viewing collected data")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="6", "Editing collected data")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="7", "Deleting collected data")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="8", "Using the webform")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="9", "Downloading data")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="10", "Downloading multimedia")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="11", "Downloading charts")
s_data_df$UpQ3l <- replace(s_data_df$UpQ3l, s_data_df$UpQ3l=="12", "Other")

#How did you hear about Ona?
s_data_df$UpQ1a <- replace(s_data_df$UpQ1a, s_data_df$UpQ1a=="1", "Suggested by a friend")
s_data_df$UpQ1a <- replace(s_data_df$UpQ1a, s_data_df$UpQ1a=="2", "Online ads")
s_data_df$UpQ1a <- replace(s_data_df$UpQ1a, s_data_df$UpQ1a=="3", "A conference  where Ona was present")
s_data_df$UpQ1a <- replace(s_data_df$UpQ1a, s_data_df$UpQ1a=="4", "Other")

s_data_df$UpQ1b <- replace(s_data_df$UpQ1b, s_data_df$UpQ1b=="1", "Suggested by a friend")
s_data_df$UpQ1b <- replace(s_data_df$UpQ1b, s_data_df$UpQ1b=="2", "Online ads")
s_data_df$UpQ1b <- replace(s_data_df$UpQ1b, s_data_df$UpQ1b=="3", "A conference  where Ona was present")
s_data_df$UpQ1b <- replace(s_data_df$UpQ1b, s_data_df$UpQ1b=="4", "Other")

s_data_df$UpQ1c <- replace(s_data_df$UpQ1c, s_data_df$UpQ1c=="1", "Suggested by a friend")
s_data_df$UpQ1c <- replace(s_data_df$UpQ1c, s_data_df$UpQ1c=="2", "Online ads")
s_data_df$UpQ1c <- replace(s_data_df$UpQ1c, s_data_df$UpQ1c=="3", "A conference  where Ona was present")
s_data_df$UpQ1c <- replace(s_data_df$UpQ1c, s_data_df$UpQ1c=="4", "Other")

s_data_df$UpQ1d <- replace(s_data_df$UpQ1d, s_data_df$UpQ1d=="1", "Suggested by a friend")
s_data_df$UpQ1d <- replace(s_data_df$UpQ1d, s_data_df$UpQ1d=="2", "Online ads")
s_data_df$UpQ1d <- replace(s_data_df$UpQ1d, s_data_df$UpQ1d=="3", "A conference  where Ona was present")
s_data_df$UpQ1d <- replace(s_data_df$UpQ1d, s_data_df$UpQ1d=="4", "Other")

#Q3. Why havent you been using Ona?
s_data_df$InQ3a <- replace(s_data_df$InQ3a, s_data_df$InQ3a=="1", "Finished my project")
s_data_df$InQ3a <- replace(s_data_df$InQ3a, s_data_df$InQ3a=="2", "Forgot my password")
s_data_df$InQ3a <- replace(s_data_df$InQ3a, s_data_df$InQ3a=="3", "I didn't know how to use it ")
s_data_df$InQ3a <- replace(s_data_df$InQ3a, s_data_df$InQ3a=="4", "Other")

s_data_df$InQ3b <- replace(s_data_df$InQ3b, s_data_df$InQ3b=="1", "Finished my project")
s_data_df$InQ3b <- replace(s_data_df$InQ3b, s_data_df$InQ3b=="2", "Forgot my password")
s_data_df$InQ3b <- replace(s_data_df$InQ3b, s_data_df$InQ3b=="3", "I didn't know how to use it ")
s_data_df$InQ3b <- replace(s_data_df$InQ3b, s_data_df$InQ3b=="4", "Other")

s_data_df$InQ3c <- replace(s_data_df$InQ3c, s_data_df$InQ3c=="1", "Finished my project")
s_data_df$InQ3c <- replace(s_data_df$InQ3c, s_data_df$InQ3c=="2", "Forgot my password")
s_data_df$InQ3c <- replace(s_data_df$InQ3c, s_data_df$InQ3c=="3", "I didn't know how to use it ")
s_data_df$InQ3c <- replace(s_data_df$InQ3c, s_data_df$InQ3c=="4", "Other")

s_data_df$InQ3d <- replace(s_data_df$InQ3d, s_data_df$InQ3d=="1", "Finished my project")
s_data_df$InQ3d <- replace(s_data_df$InQ3d, s_data_df$InQ3d=="2", "Forgot my password")
s_data_df$InQ3d <- replace(s_data_df$InQ3d, s_data_df$InQ3d=="3", "I didn't know how to use it ")
s_data_df$InQ3d <- replace(s_data_df$InQ3d, s_data_df$InQ3d=="4", "Other")

#Q2. Why did you sign up to use Ona?
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="1", "To collect data only ")
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="2", "To collect data and create charts ")
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="3", "To test XLSForms ")
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="4", "To view collected data ")
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="5", "To view charts ")
s_data_df$InQ2a <- replace(s_data_df$InQ2a, s_data_df$InQ2a=="6", "Other ")

s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="1", "To collect data only ")
s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="2", "To collect data and create charts ")
s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="3", "To test XLSForms ")
s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="4", "To view collected data ")
s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="5", "To view charts ")
s_data_df$InQ2b <- replace(s_data_df$InQ2b, s_data_df$InQ2b=="6", "Other ")

s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="1", "To collect data only ")
s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="2", "To collect data and create charts ")
s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="3", "To test XLSForms ")
s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="4", "To view collected data ")
s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="5", "To view charts ")
s_data_df$InQ2c <- replace(s_data_df$InQ2c, s_data_df$InQ2c=="6", "Other ")

s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="1", "To collect data only ")
s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="2", "To collect data and create charts ")
s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="3", "To test XLSForms ")
s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="4", "To view collected data ")
s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="5", "To view charts ")
s_data_df$InQ2d <- replace(s_data_df$InQ2d, s_data_df$InQ2d=="6", "Other ")

s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="1", "To collect data only ")
s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="2", "To collect data and create charts ")
s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="3", "To test XLSForms ")
s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="4", "To view collected data ")
s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="5", "To view charts ")
s_data_df$InQ2e <- replace(s_data_df$InQ2e, s_data_df$InQ2e=="6", "Other ")

s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="1", "To collect data only ")
s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="2", "To collect data and create charts ")
s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="3", "To test XLSForms ")
s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="4", "To view collected data ")
s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="5", "To view charts ")
s_data_df$InQ2f <- replace(s_data_df$InQ2f, s_data_df$InQ2f=="6", "Other ")

#Why did you upgrade?
s_data_df$UpQ4a<- replace(s_data_df$UpQ4a, s_data_df$UpQ4a=="1", "Reached submission limit")
s_data_df$UpQ4a<- replace(s_data_df$UpQ4a, s_data_df$UpQ4a=="2", "Wanted access to ona's advanced features")
s_data_df$UpQ4a<- replace(s_data_df$UpQ4a, s_data_df$UpQ4a=="3", "Needed support")
s_data_df$UpQ4a<- replace(s_data_df$UpQ4a, s_data_df$UpQ4a=="4", "Other")

s_data_df$UpQ4b<- replace(s_data_df$UpQ4b, s_data_df$UpQ4b=="1", "Reached submission limit")
s_data_df$UpQ4b<- replace(s_data_df$UpQ4b, s_data_df$UpQ4b=="2", "Wanted access to ona's advanced features")
s_data_df$UpQ4b<- replace(s_data_df$UpQ4b, s_data_df$UpQ4b=="3", "Needed support")
s_data_df$UpQ4b<- replace(s_data_df$UpQ4b, s_data_df$UpQ4b=="4", "Other")

s_data_df$UpQ4c<- replace(s_data_df$UpQ4c, s_data_df$UpQ4c=="1", "Reached submission limit")
s_data_df$UpQ4c<- replace(s_data_df$UpQ4c, s_data_df$UpQ4c=="2", "Wanted access to ona's advanced features")
s_data_df$UpQ4c<- replace(s_data_df$UpQ4c, s_data_df$UpQ4c=="3", "Needed support")
s_data_df$UpQ4c<- replace(s_data_df$UpQ4c, s_data_df$UpQ4c=="4", "Other")

s_data_df$UpQ4d<- replace(s_data_df$UpQ4d, s_data_df$UpQ4d=="1", "Reached submission limit")
s_data_df$UpQ4d<- replace(s_data_df$UpQ4d, s_data_df$UpQ4d=="2", "Wanted access to ona's advanced features")
s_data_df$UpQ4d<- replace(s_data_df$UpQ4d, s_data_df$UpQ4d=="3", "Needed support")
s_data_df$UpQ4d<- replace(s_data_df$UpQ4d, s_data_df$UpQ4d=="4", "Other")



setwd("C:/Users/intern/Documents")
#save file
write.csv(s_data_df,file='survey_data_clean1.csv',row.names = FALSE)
